name: owner_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.6
  get_storage: ^2.0.3
  intl: ^0.17.0
  pretty_dio_logger: any
  retrofit: any
  flutter:
    sdk: flutter
  lottie: ^1.4.2
  pie_chart: ^5.3.2
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.13
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_lints: ^1.0.0
  retrofit_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/owner-logo1.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
